### PR TITLE
Add support for combined call endpoint

### PR DESCRIPTION
**Pull request by jsullivan**
This enables users with pro or enterprise packages to still use this gem to make requests against the combined call endpoint [documented here](http://www.alchemyapi.com/api/combined/urls.html).

An optional `extract` parameter can pass in a comma separated string of features to combine when processing the request, making this endpoint especially useful for users wanting to reduce the number of requests while still getting a response containing the same data that it would normally take multiple requests to make.

### CODE REVIEW

**Comment by jsullivan** [comment]
Hm. Not sure why the build is failing, I can't see any details on the build failure unless the ALCHEMY_API env var isn't set?

**Comment by jsullivan** [comment]
Oh I see what's up. It's a style issue - Rubocop is barking about the new VCR cassettes exceeding 80 chars. Will fix.

**Comment by jsullivan** [comment]
Fixed the character length issue. Now coveralls is griping.

**Comment by johnallen3d** [comment]
Thanks for this @jsullivan, I'll get it merged and a new release out. Not sure what coveralls problem is!

**Comment by johnallen3d** [comment]
Merged offline

**Comment by johnallen3d** [comment]
[v0.7.0](https://rubygems.org/gems/alchemy-api-rb) released.

**Comment by jsullivan** [comment]
@johnallen3d great, thanks! Also, I'm not sure but maybe this takes care of one of the to-dos in the Readme? #3?

https://github.com/technekes/alchemy-api-rb#todo

**Comment by johnallen3d** [comment]
Ah, good catch! I'll update that as well. Thanks again!

**Pull request closed without merging**
